import type { Metadata } from "next";
import "./globals.css";

// import localFont from "next/font/local";

// Define the local font.
// const general = localFont({
//   src: "../public/fonts/general.woff2", // Use the correct file path and name
//   variable: "--font-general-sans",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
